// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID           int32
	Username     string
	PasswordHash string
}

type Product struct {
	ID          int32
	Name        string
	Description sql.NullString
	ImageUrl    string
	Price       string
	StockCount  int32
	CreatedAt   time.Time
}
