// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package repository

import (
	"context"
	"database/sql"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name, description, image_url, price, stock_count
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, name, description, image_url, price, stock_count, created_at
`

type CreateProductParams struct {
	Name        string
	Description sql.NullString
	ImageUrl    string
	Price       string
	StockCount  int32
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.ImageUrl,
		arg.Price,
		arg.StockCount,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.StockCount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getAdminByUsername = `-- name: GetAdminByUsername :one

SELECT id, username, password_hash FROM admins
WHERE username = $1 LIMIT 1
`

// db/query.sql
func (q *Queries) GetAdminByUsername(ctx context.Context, username string) (Admin, error) {
	row := q.db.QueryRowContext(ctx, getAdminByUsername, username)
	var i Admin
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const getAllProducts = `-- name: GetAllProducts :many
SELECT id, name, description, image_url, price, stock_count, created_at FROM products
ORDER BY created_at DESC
`

func (q *Queries) GetAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Price,
			&i.StockCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAvailableProducts = `-- name: GetAvailableProducts :many
SELECT id, name, description, image_url, price, stock_count, created_at FROM products
WHERE stock_count > 0
ORDER BY created_at DESC
`

func (q *Queries) GetAvailableProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAvailableProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.Price,
			&i.StockCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, description, image_url, price, stock_count, created_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int32) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.StockCount,
		&i.CreatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET stock_count = $2
WHERE id = $1
RETURNING id, name, description, image_url, price, stock_count, created_at
`

type UpdateProductStockParams struct {
	ID         int32
	StockCount int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProductStock, arg.ID, arg.StockCount)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.Price,
		&i.StockCount,
		&i.CreatedAt,
	)
	return i, err
}
